<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('escasia');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/home.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/button.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/font.css'); ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("#main").css("display", "none");
                $("#main").fadeIn(300);
            });
        </script>
    </head>
    <!-- End of Head -->

    <!-- Begin of Main Body -->
    <body>
       
            <?php echo $this->layout()->content; ?> <!-- Content of this Layout (Homepage) -->
            
      

    </body>
    <!-- End of Body -->
</html>